version: '3'
services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - 'pg:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: xrt_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  pg:
