version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.10
        environment:
          MIX_ENV: test
          DB_HOST: localhost
          DB_USER: postgres
          DB:PASSWORD: postgres
          DB_NAME: xrt_test
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: xrt_test
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "mix.lock" }}
            - v1-dependency-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix ecto.migrate
      - run: mix credo
      - run:
          command: MIX_ENV=dev mix dialyzer --plt
          no_output_timeout: 20m
      - run: mix test
      - save_cache:
          key: v1-dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
